### ISSUE TITLE
Add a mode for quantized floats

### ISSUE THREAD

**Issue by bzinberg** [mwlon/pcodec#191]
_Suggested issue labels: Feature request ("Enhancement" in GitHub iirc), Good first issue.  This is an onboarding issue for @bzinberg (me)._

## Motivation

One use case that Pco is well-positioned to add support for is "quantized floats" -- collections of floats whose values don't use the full precision available in the data type.  This happens e.g. when a data set enters a processing pipeline as `f16`s and somewhere along the way gets widened to `f32`s.  The unused precision bits in these `f32`s are all the same, and can be compressed.

## Implementation plan

@mwlon suggested the following sequence of steps:

1. Add a [synthetic dataset](https://github.com/mwlon/pcodec/tree/f9a696ff96e860cc209cd52d7a75dde3bf1a1304/pco_cli#setting-up-synthetic-data) that should be compressible under this mode, e.g., casting a bunch of `f16` normals to `f32`
2. Add the new mode to [`mode.rs`](https://github.com/mwlon/pcodec/blob/f9a696ff96e860cc209cd52d7a75dde3bf1a1304/pco/src/mode.rs), taking a `Bitlen` (alias for `u32`) as argument, and write decoding logic for [floats](https://github.com/mwlon/pcodec/blob/f9a696ff96e860cc209cd52d7a75dde3bf1a1304/pco/src/data_types/floats.rs#L211)
3. Add encoding logic. This part is more involved, but can probably reuse some logic from `float_mult`.

## Testing plan

TBD, will follow up.

**Comment by mwlon** [comment]
Yep, this should substantially improve compression ratio for f16s represented as f32s in most cases. Orthogonally, we're likely to add f16s support at the API level, so you won't have to explicitly cast to f32. No one has started on this 2nd task yet - would you like to? It shouldn't be too hard.

**Comment by Skielex** [comment]
Sounds promising. I'd like to help if I can, but like I said I might be a bit out of my depth here. I haven't really used Rust beyond Hello World and compression is not my field of expertise - my background is software engineering and computer vision, mainly using C-languages and Python.

That said I've been looking for an excuse to get my hands rusty, so if you don't mind, I can give it a shot. However, I'll need guidance on where to start and how you want to deal with `f16` in general, since the type isn't natively supported as far as I can tell. Also, I'm not sure exactly the work would integrate with the ongoing draft PR. I don't want to waste your time, so I'll leave it to you as to whether you think it's worth it to involve a newbie (me). 

If you're interested I can probably provide some `f16` datasets for testing. The datasets would consist of real-world ultrasound data (A-scans) collected on composites, metal, and/or plexiglass. The data is stored as frames consisting of one or more A-scans (typically 1-1000), with each A-scan consisting of a number of amplitude values (say 200-4000) stored as `f16`. The frames would be stored in a binary format of our choice with one or more headers describing the frames.

I joined the Discord if you want to continue the discussion there.

**Comment by mwlon** [comment]
Implemented in #193

**Comment by mwlon** [comment]
Implemented in https://github.com/mwlon/pcodec/pull/193

**Comment by bzinberg** [comment]
For posterity,

> ## Testing plan
> 
> TBD, will follow up.

Testing plan ended up being as noted in the PR description:
* Unit tests for `float_quant_utils`
* E2E compress -> decompress round trip in `src/tests/recovery.rs`
* Running `bench` to see that FloatQuant beats FloatMult on the `quantized_normal` dataset
